const explore = (req, res) => {
  const exploredata = [
    {
      id: 1,
      title: "Aryan valvi",
      pandya: "/img1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/profile.png",
      des: "mobile design...",
      liked: false,
    },
    {
      id: 2,
      title: "Armin",
      pandya: "/armin-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img2 1.png",
      des: "shop...",
      liked: false,
    },
    {
      id: 3,
      title: "Dariba",
      pandya: "/darina-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img3 1.png",
      des: "web design...",
      liked: false,
    },
    {
      id: 4,
      title: "Aryan valvi",
      pandya: "/img1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/profile.png",
      des: "mobile design...",
      liked: false,
    },
    {
      id: 5,
      title: "Armin",
      pandya: "/armin-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img2 1.png",
      des: "shop...",
      liked: false,
    },
    {
      id: 6,
      title: "Dariba",
      pandya: "/darina-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img3 1.png",
      des: "web design...",
      liked: false,
    },
    {
      id: 7,
      title: "Armin",
      pandya: "/armin-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img2 1.png",
      des: "shop...",
      liked: false,
    },
    {
      id: 8,
      title: "Dariba",
      pandya: "/darina-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img3 1.png",
      des: "web design...",
      liked: false,
    },
    {
      id: 9,
      title: "Armin",
      pandya: "/armin-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img2 1.png",
      des: "shop...",
      liked: false,
    },
    {
      id: 10,
      title: "Dariba",
      pandya: "/darina-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img3 1.png",
      des: "web design...",
      liked: false,
    },
    {
      id: 11,
      title: "Armin",
      pandya: "/armin-gand 1.png",
      save: "/save.svg",
      like: "/like.svg",
      view: "/views.svg",
      profile: "/img2 1.png",
      des: "shop...",
      liked: false,
    },
  ];
  res.json(exploredata);
};

module.exports = explore;
